# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 697)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.main_tab = QtWidgets.QWidget()
        self.main_tab.setObjectName("main_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choose_company_button = QtWidgets.QPushButton(self.main_tab)
        self.choose_company_button.setObjectName("choose_company_button")
        self.horizontalLayout.addWidget(self.choose_company_button)
        self.checked_comapny_label = QtWidgets.QLabel(self.main_tab)
        self.checked_comapny_label.setLineWidth(1)
        self.checked_comapny_label.setText("")
        self.checked_comapny_label.setWordWrap(True)
        self.checked_comapny_label.setObjectName("checked_comapny_label")
        self.horizontalLayout.addWidget(self.checked_comapny_label)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.units_list_listWidget = QtWidgets.QListWidget(self.main_tab)
        self.units_list_listWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.units_list_listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.units_list_listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.units_list_listWidget.setObjectName("units_list_listWidget")
        self.gridLayout_2.addWidget(self.units_list_listWidget, 0, 2, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.choose_items_button = QtWidgets.QPushButton(self.main_tab)
        self.choose_items_button.setObjectName("choose_items_button")
        self.verticalLayout.addWidget(self.choose_items_button)
        self.checked_items_listWidget = QtWidgets.QListWidget(self.main_tab)
        self.checked_items_listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.checked_items_listWidget.setObjectName("checked_items_listWidget")
        self.verticalLayout.addWidget(self.checked_items_listWidget)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.add_one_unit_button = QtWidgets.QPushButton(self.main_tab)
        self.add_one_unit_button.setObjectName("add_one_unit_button")
        self.verticalLayout_2.addWidget(self.add_one_unit_button)
        self.delete_one_unit_button = QtWidgets.QPushButton(self.main_tab)
        self.delete_one_unit_button.setObjectName("delete_one_unit_button")
        self.verticalLayout_2.addWidget(self.delete_one_unit_button)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.all_company_price_listWidgets = QtWidgets.QListWidget(self.main_tab)
        self.all_company_price_listWidgets.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.all_company_price_listWidgets.setObjectName("all_company_price_listWidgets")
        self.gridLayout_3.addWidget(self.all_company_price_listWidgets, 0, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(578, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.save_to_monthly_statistic_button = QtWidgets.QPushButton(self.main_tab)
        self.save_to_monthly_statistic_button.setObjectName("save_to_monthly_statistic_button")
        self.gridLayout_3.addWidget(self.save_to_monthly_statistic_button, 1, 2, 1, 1)
        self.save_to_file_button = QtWidgets.QPushButton(self.main_tab)
        self.save_to_file_button.setObjectName("save_to_file_button")
        self.gridLayout_3.addWidget(self.save_to_file_button, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.main_tab, "")
        self.coms_items_tab = QtWidgets.QWidget()
        self.coms_items_tab.setObjectName("coms_items_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.coms_items_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.com_label = QtWidgets.QLabel(self.coms_items_tab)
        self.com_label.setEnabled(True)
        self.com_label.setObjectName("com_label")
        self.gridLayout.addWidget(self.com_label, 0, 0, 1, 1)
        self.com_lineEdit = QtWidgets.QLineEdit(self.coms_items_tab)
        self.com_lineEdit.setText("")
        self.com_lineEdit.setObjectName("com_lineEdit")
        self.gridLayout.addWidget(self.com_lineEdit, 0, 1, 1, 2)
        self.com_add_pushButton = QtWidgets.QPushButton(self.coms_items_tab)
        self.com_add_pushButton.setObjectName("com_add_pushButton")
        self.gridLayout.addWidget(self.com_add_pushButton, 1, 0, 1, 1)
        self.com_del_pushButton = QtWidgets.QPushButton(self.coms_items_tab)
        self.com_del_pushButton.setObjectName("com_del_pushButton")
        self.gridLayout.addWidget(self.com_del_pushButton, 1, 2, 1, 1)
        self.page2_com_listWidget = QtWidgets.QListWidget(self.coms_items_tab)
        self.page2_com_listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.page2_com_listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.page2_com_listWidget.setObjectName("page2_com_listWidget")
        self.gridLayout.addWidget(self.page2_com_listWidget, 2, 0, 1, 3)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.coms_items_tab)
        self.line.setEnabled(False)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 0, 1, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.item_lineEdit = QtWidgets.QLineEdit(self.coms_items_tab)
        self.item_lineEdit.setText("")
        self.item_lineEdit.setObjectName("item_lineEdit")
        self.gridLayout_8.addWidget(self.item_lineEdit, 0, 1, 1, 2)
        self.item_label = QtWidgets.QLabel(self.coms_items_tab)
        self.item_label.setEnabled(True)
        self.item_label.setObjectName("item_label")
        self.gridLayout_8.addWidget(self.item_label, 0, 0, 1, 1)
        self.price_label = QtWidgets.QLabel(self.coms_items_tab)
        self.price_label.setEnabled(True)
        self.price_label.setObjectName("price_label")
        self.gridLayout_8.addWidget(self.price_label, 1, 0, 1, 1)
        self.item_price_del_pushButton = QtWidgets.QPushButton(self.coms_items_tab)
        self.item_price_del_pushButton.setObjectName("item_price_del_pushButton")
        self.gridLayout_8.addWidget(self.item_price_del_pushButton, 2, 2, 1, 1)
        self.item_price_spinBox = QtWidgets.QSpinBox(self.coms_items_tab)
        self.item_price_spinBox.setMaximum(999999999)
        self.item_price_spinBox.setObjectName("item_price_spinBox")
        self.gridLayout_8.addWidget(self.item_price_spinBox, 1, 1, 1, 2)
        self.item_price_add_pushButton = QtWidgets.QPushButton(self.coms_items_tab)
        self.item_price_add_pushButton.setObjectName("item_price_add_pushButton")
        self.gridLayout_8.addWidget(self.item_price_add_pushButton, 2, 0, 1, 1)
        self.page2_item_price_listWidget = QtWidgets.QListWidget(self.coms_items_tab)
        self.page2_item_price_listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.page2_item_price_listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.page2_item_price_listWidget.setObjectName("page2_item_price_listWidget")
        self.gridLayout_8.addWidget(self.page2_item_price_listWidget, 3, 0, 1, 3)
        self.gridLayout_4.addLayout(self.gridLayout_8, 0, 2, 1, 1)
        self.save_to_ini_button = QtWidgets.QPushButton(self.coms_items_tab)
        self.save_to_ini_button.setObjectName("save_to_ini_button")
        self.gridLayout_4.addWidget(self.save_to_ini_button, 1, 0, 1, 3)
        self.tabWidget.addTab(self.coms_items_tab, "")
        self.monthly_statistic = QtWidgets.QWidget()
        self.monthly_statistic.setObjectName("monthly_statistic")
        self.layoutWidget = QtWidgets.QWidget(self.monthly_statistic)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 761, 611))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.page3_calendarWidget = QtWidgets.QCalendarWidget(self.layoutWidget)
        self.page3_calendarWidget.setObjectName("page3_calendarWidget")
        self.gridLayout_12.addWidget(self.page3_calendarWidget, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_12.addWidget(self.label_5, 0, 0, 1, 2)
        self.page3_monthly_listWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.page3_monthly_listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.page3_monthly_listWidget.setObjectName("page3_monthly_listWidget")
        self.gridLayout_12.addWidget(self.page3_monthly_listWidget, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_12.addWidget(self.label_6, 6, 0, 1, 2)
        self.page3_daily_listWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.page3_daily_listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.page3_daily_listWidget.setObjectName("page3_daily_listWidget")
        self.gridLayout_12.addWidget(self.page3_daily_listWidget, 7, 1, 1, 1)
        self.page3_monthly_download_button = QtWidgets.QPushButton(self.layoutWidget)
        self.page3_monthly_download_button.setObjectName("page3_monthly_download_button")
        self.gridLayout_12.addWidget(self.page3_monthly_download_button, 2, 1, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.page3_start_label = QtWidgets.QLabel(self.layoutWidget)
        self.page3_start_label.setObjectName("page3_start_label")
        self.gridLayout_11.addWidget(self.page3_start_label, 0, 0, 1, 1)
        self.page3_end_label = QtWidgets.QLabel(self.layoutWidget)
        self.page3_end_label.setObjectName("page3_end_label")
        self.gridLayout_11.addWidget(self.page3_end_label, 1, 0, 1, 1)
        self.page3_end_dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.page3_end_dateEdit.setObjectName("page3_end_dateEdit")
        self.gridLayout_11.addWidget(self.page3_end_dateEdit, 1, 1, 1, 1)
        self.page3_start_dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.page3_start_dateEdit.setObjectName("page3_start_dateEdit")
        self.gridLayout_11.addWidget(self.page3_start_dateEdit, 0, 1, 1, 1)
        self.page3_all_date_label = QtWidgets.QLabel(self.layoutWidget)
        self.page3_all_date_label.setObjectName("page3_all_date_label")
        self.gridLayout_11.addWidget(self.page3_all_date_label, 2, 0, 1, 1)
        self.page3_alldates_listWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.page3_alldates_listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.page3_alldates_listWidget.setObjectName("page3_alldates_listWidget")
        self.gridLayout_11.addWidget(self.page3_alldates_listWidget, 3, 0, 1, 2)
        self.page3_monthly_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.page3_monthly_pushButton.setObjectName("page3_monthly_pushButton")
        self.gridLayout_11.addWidget(self.page3_monthly_pushButton, 2, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 1, 0, 3, 1)
        self.tabWidget.addTab(self.monthly_statistic, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choose_company_button.setText(_translate("MainWindow", "选择公司"))
        self.choose_items_button.setText(_translate("MainWindow", "选择检查项目"))
        self.checked_items_listWidget.setSortingEnabled(True)
        self.add_one_unit_button.setText(_translate("MainWindow", "添加 ->"))
        self.delete_one_unit_button.setText(_translate("MainWindow", "删除"))
        self.all_company_price_listWidgets.setSortingEnabled(True)
        self.save_to_monthly_statistic_button.setText(_translate("MainWindow", "存入月度统计"))
        self.save_to_file_button.setText(_translate("MainWindow", "下载今日数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main_tab), _translate("MainWindow", "主页"))
        self.com_label.setText(_translate("MainWindow", "公司名："))
        self.com_add_pushButton.setText(_translate("MainWindow", "添加 "))
        self.com_del_pushButton.setText(_translate("MainWindow", "删除"))
        self.item_label.setText(_translate("MainWindow", "检查项目名："))
        self.price_label.setText(_translate("MainWindow", "价格："))
        self.item_price_del_pushButton.setText(_translate("MainWindow", "删除"))
        self.item_price_add_pushButton.setText(_translate("MainWindow", "添加 "))
        self.save_to_ini_button.setText(_translate("MainWindow", "保存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.coms_items_tab), _translate("MainWindow", "修改公司/检查项目"))
        self.label_5.setText(_translate("MainWindow", "月度统计："))
        self.label_6.setText(_translate("MainWindow", "单日记录："))
        self.page3_monthly_download_button.setText(_translate("MainWindow", "下载月度统计！"))
        self.page3_start_label.setText(_translate("MainWindow", "开始日期："))
        self.page3_end_label.setText(_translate("MainWindow", "截至日期："))
        self.page3_all_date_label.setText(_translate("MainWindow", "统计日期："))
        self.page3_monthly_pushButton.setText(_translate("MainWindow", "Go!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.monthly_statistic), _translate("MainWindow", "月度统计"))

