# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 690)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choose_company_button = QtWidgets.QPushButton(self.centralwidget)
        self.choose_company_button.setObjectName("choose_company_button")
        self.horizontalLayout.addWidget(self.choose_company_button)
        self.checked_comapny_label = QtWidgets.QLabel(self.centralwidget)
        self.checked_comapny_label.setLineWidth(1)
        self.checked_comapny_label.setText("")
        self.checked_comapny_label.setWordWrap(True)
        self.checked_comapny_label.setObjectName("checked_comapny_label")
        self.horizontalLayout.addWidget(self.checked_comapny_label)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.units_list_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.units_list_listWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.units_list_listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.units_list_listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.units_list_listWidget.setObjectName("units_list_listWidget")
        self.gridLayout_2.addWidget(self.units_list_listWidget, 0, 2, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.choose_items_button = QtWidgets.QPushButton(self.centralwidget)
        self.choose_items_button.setObjectName("choose_items_button")
        self.verticalLayout.addWidget(self.choose_items_button)
        self.checked_items_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.checked_items_listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.checked_items_listWidget.setObjectName("checked_items_listWidget")
        self.verticalLayout.addWidget(self.checked_items_listWidget)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.add_one_unit_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_one_unit_button.setObjectName("add_one_unit_button")
        self.verticalLayout_2.addWidget(self.add_one_unit_button)
        self.delete_one_unit_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_one_unit_button.setObjectName("delete_one_unit_button")
        self.verticalLayout_2.addWidget(self.delete_one_unit_button)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.all_company_price_listWidgets = QtWidgets.QListWidget(self.centralwidget)
        self.all_company_price_listWidgets.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.all_company_price_listWidgets.setObjectName("all_company_price_listWidgets")
        self.gridLayout_3.addWidget(self.all_company_price_listWidgets, 0, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(578, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.save_to_monthly_statistic_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_to_monthly_statistic_button.setObjectName("save_to_monthly_statistic_button")
        self.gridLayout_3.addWidget(self.save_to_monthly_statistic_button, 1, 2, 1, 1)
        self.save_to_file_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_to_file_button.setObjectName("save_to_file_button")
        self.gridLayout_3.addWidget(self.save_to_file_button, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 29))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choose_company_button.setText(_translate("MainWindow", "选择公司"))
        self.choose_items_button.setText(_translate("MainWindow", "选择检查项目"))
        self.checked_items_listWidget.setSortingEnabled(True)
        self.add_one_unit_button.setText(_translate("MainWindow", "添加 ->"))
        self.delete_one_unit_button.setText(_translate("MainWindow", "删除"))
        self.all_company_price_listWidgets.setSortingEnabled(True)
        self.save_to_monthly_statistic_button.setText(_translate("MainWindow", "存入月度统计"))
        self.save_to_file_button.setText(_translate("MainWindow", "下载今日数据"))
        self.menu.setTitle(_translate("MainWindow", "主页"))
        self.menu_2.setTitle(_translate("MainWindow", "修改公司/检查项目"))
        self.menu_3.setTitle(_translate("MainWindow", "月度统计"))

